# Nginx Configuration for ${environment}
# Generated by Terraform

server {
    listen ${port};
    server_name ${server_name};

    location / {
        proxy_pass http://backend:${backend_port};
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /health {
        access_log off;
        return 200 "healthy\n";
        add_header Content-Type text/plain;
    }
}
